remote_theme: chrisrhymes/bulma-clean-theme

lang: en
title: Bulma Clean Theme
tagline: Bulma Clean Theme
email: fernando.monroy.mtz@hotmail.com
description: >
  Game developer and Software Engineer 
