remote_theme: chrisrhymes/bulma-clean-theme

lang: en
title: Fernando Monroy
tagline: Fernando Monroy
email: fernando.monroy.mtz@hotmail.com
description: >
  Senior software engineer
permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
